# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: test
    - run: echo Starting Test
    -  run:  npm ci
    -  run:  npm test
    -  run:  npm run build
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest windows-latest macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/heroku@master
    - uses: build
    # Runs a set of commands using the runners shell
    - name: deploy
    - run: echo Starting Deployment to Heroku
    -  run:  git heroku master https://git.heroku.com/cicdtutorial1.git
    -  run:  git add.
    -  run:  git commit -m "Deployment Through GitActions"     
    -  run:  git push heroku master

